---
title: "lab1"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
dados <- read_csv("../data/brasileirao_2026.csv")
```

```{r}
head(dados)
```

Caminho para pasta com resultados

```{r}
resultados_path <- "../data/resultados/"
```

1.  Tratando dados, separando em partidas realizadas e partidas futuras

```{r}
source("tratar_dados.R")
source("extrair_jogos_futuros.R")

dados_tratados <- tratar_dados(dados)
jogos_futuros <- extrair_jogos_futuros(dados)
```

2.  Gerando tabela com thetas e phis

```{r}
source("estimar_parametros.R")

parametros <- estimar_parametros(dados_tratados)
```

3.  Gerando tabela de classificação

```{r}
source("classificar_times.R")

classificacao_atual <- classificar_times(dados_tratados)
```

```{r}
source("inicializar_acumuladores.R")
source("atualizar_acumuladores.R")

```

```{r}
source("formatar_resultados.R")
source("monte_carlo_campeonato.R")
source("simular_jogos.R")
```



```{r}
resultados_mc <- monte_carlo_campeonato(
    dados_tratados= dados_tratados,
    jogos_futuros = jogos_futuros,
    parametros = parametros,
    B = 10000
)
```

Resultado:
```{r}
resultados_mc
```

---

Bootstrap:

```{r}
# funções do bootstrap
source("bootstrap_time.R")
source("resumir_bootstrap.R")
source("bootstrap_campeonato.R")
source("plotar_bootstrap.R")
```

```{r}
# B replicações
B_boot <- 10000

resultados_bootstrap <- bootstrap_campeonato(
  dados_tratados = dados_tratados,
  parametros = parametros,
  B = B_boot,
  nivel = 0.95
)

resultados_bootstrap
```


```{r}
grafico_bootstrap <- plotar_bootstrap(
  resultados_bootstrap
)

grafico_bootstrap
```


Persistindo resultados:
```{r}
write_csv(
  resultados_bootstrap,
  file.path(
    resultados_path,
    "resultados_bootstrap.csv"
  )
)

ggsave(
  filename = file.path(
    resultados_path,
    "intervalos_bootstrap.png"
  ),
  plot = grafico_bootstrap,
  width = 10,
  height = 8,
  dpi = 300
)
```


A.  Gerando outputs

```{r}
write_csv(
  parametros,
  file = file.path(resultados_path, "parametros.csv")
)

write_csv(
  classificacao_atual,
  file = file.path(resultados_path, "classificacao_atual.csv")
)
```
